name: "Network Tracker Zones"
description: "Assign an associated zone to new UniFi Network and MikroTik Router client trackers."
version: "0.1.0"
slug: network_tracker_zones
init: false
boot: auto
homeassistant_api: true
arch:
  - amd64
  - aarch64
options:
  mappings: []
schema:
  mappings:
    - source_entry_id: str
      zone: str
